### ISSUE TITLE
Very good article, but unfortunately the code is written in pytorch-lightning framework

### ISSUE THREAD

**Issue by Lixuanhe** [savvaki/LPDM#3]

**Comment by savvaki** [comment]
I am sorry that this disappoints you. PyTorch lighting (PL) is actually only used because the original [Stable Diffusion repo](https://github.com/CompVis/stable-diffusion) used PL, and this is a fork of that repo. The good news is that the PL is just a different way to organize normal pytorch, see [here](https://lightning.ai/docs/pytorch/stable/starter/converting.html) some of the differences. The model weights are actually the same as normal pytorch, you could technically convert the one to the other with some effort, see [here](https://stackoverflow.com/questions/71039820/retrieve-the-pytorch-model-from-a-pytorch-lightning-model).

Otherwise which framework would you have preferred?

Thank you for your interest!

**Comment by Lixuanhe** [comment]
Thank you for your patience in replying. I have not used pytorch-lightning before and the code looks a bit different from pytorch, but I believe pytorch-lightning is easy to get started.

**Comment by savvaki** [comment]
I also had to get used to PL myself. Personally I prefer normal PyTorch, but since this is a fork I had to get used to it. Honestly, PL makes it much easier to rapidly experiment. The reason is that the training loop is now _part of the model_ in PL. This makes it easy to change the training loop for _each model_ you make. In normal PyTorch, the same training loop is used for all your models, and this makes it much messier than PL when you need to change that training loop. 

I would recommend looking at [this video](https://www.youtube.com/watch?v=f6PtJKdey8E&ab_channel=AleksaGordi%C4%87-TheAIEpiphany) where The AI Epiphany explains the original code that this repo is forked from.

**Comment by Lixuanhe** [comment]
Thank you very much！
