### ISSUE TITLE
train

### ISSUE THREAD

**Issue by sunwarm2001** [savvaki/LPDM#4]
Hello! Thanks for your code, and i have a doubt:
In the train, you say: "To reduce the size of the model, reduce the model_channels parameter in configs/train/lpdm_lol.yaml"
Is the `image_size` should be the same as `model_channels`？I see in the `lpdm_lol.yaml` that they are 256 and 128 respectively.

**Comment by savvaki** [comment]
Hi,

The `model_channels` is how many output channels each residual block has within the model. This directly reduces the number of parameters. The input and output shapes and channels remain the same (those parameters are set by `in_channels` and `out_channels` respectively . The `image_size` you can ignore as it is unrelated (the model doesn't even use this parameter as far as I remember). Also note that since it is a UNet, the height and width of the input image should be divisible by 2^3=8 since there are 3 downsampling layers.  You can change the training and validation crop size by setting the `crop_size` parameter.

Hope this answers your question :)

**Comment by sunwarm2001** [comment]
Thanks for your reply, it does address my concern!
But please allow me to ask further. I want to fine-tune the training model and what parameters do I need to pay attention to？
Now I'm trying `timesteps` of 800,1200, but it does a little work.

**Comment by savvaki** [comment]
The `timesteps` you shouldn't really change. The `timesteps` is the variable $T$ from the paper which defines how many steps the diffusion model is trained to remove. So on a scale from "zero noise" to "pure noise", there are 1000 small steps. When training, timesteps are randomly sampled in the range $t \in$ [0, `timesteps`], so this means $t \in$ [0, 1000], where 1000 is pure noise and 0 is zero noise.  In order for the model to understand what $t$ is, $t$ is embedded into a vector form, so that the model knows exactly which timestep it needs to predict noise for. 

So for example:  the model ($\epsilon_\theta$) takes two parameters: $\epsilon_\theta( x_t \oplus c, t_{embedded})$, where $x_t$ is the bright image but with added noise at level $t$, $c$ is the dark image, $t_{embedded}$ is the embedded timestep information, and $\oplus$ is the concatenation operator. 

When finetuning the model, make sure that your dataset  is being read in correctly. So that is the `data` part of the config.  

Keep in mind that this model does **_not_** use the reverse diffusion process (i.e. sampling $x_T \sim \mathcal{N}(0, 1)$ and then iteratively going from $t = 1000$ to $t = 0$). This is the contribution of the paper: that we just use the diffusion model to extract noise features in one pass through the model, so there is no need for the reverse process.
